Macrometacorp/docs

docs/demos/streamlit-oxford.md
mkdocs.yml

In this pr i have added oxford-economics in the demo page.

Add oxford economics in the demo page

---

mkdocs.yml

There were some broken and missing links in the menus. This should fix those

update yml to fix broken links and include missing links

---

docs/quickstart.md
mkdocs.yml

This improves the getting started guide

updates to the getting started guide

---

docs/documents/tutorials/overview.md
mkdocs.yml

This pr is related to this 
https://github.com/Macrometacorp/C8Platform/issues/2856

Hide triggering flows

---

docs/quotas.md

Update and streamline the Quotas and Limits table to provide a more complete view of Free vs. Metered limits, and also to make the information easier to compare.

Update Quotas and Limits table

---

docs/search/Views.md

Some nested bullet lists did not render properly on the website.  Updated the spacing to fix the nested lists.  @elof

Fixed incorrect spacing in bullet list

---

docs/search/tutorials/using-rest-api.md

@elof I corrected a typo in the Pre-requisite item in the table of contents.

Correcting Typo in Table of Contents

---

docs/search/Views.md

@elof Fixed a broken URL by adding a `/` to the end.

Views URL Correction

---

docs/keyvalue/tutorials/using-rest-api.md

Fix made on all federation URLs

Updating federatiomn URLs

---

docs/keyvalue/tutorials/bulk-update-restql.md

Fix made on the FEDERATION URL link for Rest API code sample

Updated Rest API FEDERATION URL

---

docs/documents/tutorials/bulk-update-restql.md

Fixing FEDERATION URL link in Rest API code sample

Updateing FEDERATION URL link

---

docs/streams/quickstart.md

Fixing the FEDERATION URL in Pub-Sub with streams in browser

Updating FEDERATION URL

---

docs/quotas.md

Removing  Requests per Second limit as there is no such a document in our DB

Removing Requests per Second line

---

docs/c8ql/transactions/limitations.md

Fixed intext link for Locking and Isolation, line 29

Fixed intext link

---

docs/c8ql/transactions/transaction-invocation.md

Fixed intext link for Transactions Locking, line 58

Fixing intext link

---

docs/documents/appendix/errorcodes.md

Revert "Remove transaction errors from errorcode page"

---

docs/c8ql/transactions/limitations.md

Revert "Fixed intext link"

---

docs/demos/credit-card-fraud.md

Broken link to fraud detection app

Broken link to fraud detection app

---

docs/demos/crypto-trading.md

Stream workers released note and current restrictions added to doc.

Stream Workers release note added

---

docs/cep/reference/geospatial.md

Sorry @elof - looks like the Geospatial doc itself got reverted too 😞 Opening this PR to add the doc itself back in.

Geospatial

---

docs/documents/tutorials/using_rest_api.md

Revised API tutorial for concision and clarity.  CURL examples forthcoming.
@elof These changes have been reviewed and are approved.

Update API tutorial

---

docs/restql/concepts.md
docs/restql/tutorial.md

Revised Query Worker sections for concision and clarity.
@elof These changes have been reviewed and are approved.

Query Worker revisions

---

docs/keyvalue/quickstart.md
docs/keyvalue/tutorials/bulk-update-restql.md
docs/keyvalue/tutorials/using-rest-api.md

Revisions to Key-Value sections for concision and clarity.  CURL examples forthcoming.
@elof FYI This content has already been reviewed and approved.

Revise Key-Value docs

---

docs/documents/indexing/index-basics.md
docs/documents/indexing/working-with-indexes.md

Update Indexing docs to partially replace Arango Shell samples with CURL samples.

Update Indexing docs

---

docs/demos/posthog.md
mkdocs.yml

Hi @VikasPatel - can you please review the following content related to PostHog analytics integration and let me know if this looks correct?  In particular, do we need to add anything to Step 1 when users follow Integrate PostHog docs?
cc @macrochrissie

Added PostHog tutorial

---

docs/documents/appendix/glossary.md

Updating GeoFabric glossary text and adding a link to the GeoFabric blog post.

Update GeoFabric glossary text

---

docs/cep/quickstart.md

Made correction to argument passed in the client.validate_stream_app() function.

Update to CEP Quickstart

---

docs/c8ql/functions/miscellaneous.md

Updated Query Worker docs to include User-Based Access Control functions.  This is planned for 17.8.
@joubert-macrometa Can you please review the changes and verify that my descriptions are correct?
@macrochrissie Feel free to review this one if you'd like!  This is planned for 17.8.

Added User-Based Access Control functions

---

docs/gdnsl/commands.md
docs/gdnsl/overview.md
docs/gdnsl/tutorials/autoscaling.md
docs/gdnsl/tutorials/gettingstarted.md
docs/gdnsl/tutorials/management.md
docs/gdnsl/tutorials/trafficsplitting.md
docs/gdnsl/tutorials/workflows.md
mkdocs.yml

Added docs for GDNSL Command Line Interface (CLI)

Command line interface docs

---

docs/cep/reference/limits.md
mkdocs.yml

Added documentation for new CEP limits.

Add CEP Limits docs

---

docs/cep/reference/functions.md

Hi @grainier-macrometa - can you please review the changes in the Functions doc for accuracy?  I've updated an extensive list of CEP function examples.  Please let me know if you have any questions or concerns.  Thanks!

Update CEP Functions
